### ISSUE TITLE
Tests not usable as (Debian CI) runtime tests

### ISSUE THREAD

**Issue by olebole** [astrofrog/wcsaxes#161]
Hi,

I am trying to setup the tests provided by wcsaxes for the use in the Debian CI system. However, when running on the installed package, I get the following error:
```
=================================== FAILURES ===================================
_________________________ TestBasic.test_ticks_labels __________________________

self = <wcsaxes.tests.test_images.TestBasic object at 0x7fc95bd64a50>
generate = None

    def test_ticks_labels(self, generate):
[...]
        self.generate_or_test(generate, fig, 'ticks_labels.png',
>                             bbox_inches='tight')

/usr/lib/python2.7/dist-packages/wcsaxes/tests/test_images.py:266: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <wcsaxes.tests.test_images.TestBasic object at 0x7fc95bd64a50>
generate = None, figure = <matplotlib.figure.Figure object at 0x7fc95bd64a10>
image = 'ticks_labels.png', bbox_inches = 'tight'

    def generate_or_test(self, generate, figure, image, bbox_inches=None):
            if msg is None:
                shutil.rmtree(result_dir)
            else:
[...]
>               raise Exception(msg)
E               Exception: Error: Image files did not match.
E                 RMS Value: 17.7928397195
E                 Expected:  
E                   /tmp/tmpCC8TzI/baseline-ticks_labels.png
E                 Actual:    
E                   /tmp/tmpCC8TzI/ticks_labels.png
E                 Difference:
E                   /tmp/tmpCC8TzI/ticks_labels-failed-diff.png
E                 Tolerance: 
E                   1.5

/usr/lib/python2.7/dist-packages/wcsaxes/tests/test_images.py:68: Exception
```
where the axes and fonts in the images differ by a few pixels. If I install the package on Ubuntu, I get lots more of these errors.

This is different from #130 since I dont use a local `.matplotlib` directory.

**Comment by astrofrog** [comment]
@olebole - could you give me the exact versions of packages you are using? (in particular matplotlib), and could you also send me the /tmp/tmpCC8TzI/ticks_labels.png file?

**Comment by olebole** [comment]
Am 10.05.2015 um 17:21 schrieb Thomas Robitaille:
> @olebole <https://github.com/olebole> - could you give me the exact versions
> of packages you are using? (in particular matplotlib), and could you also
> send me the /tmp/tmpCC8TzI/ticks_labels.png file?

Sure: the ticks_labels file is attached. The test header says:

platform linux2 -- Python 2.7.9 -- pytest-2.5.1

Running tests with Astropy version 0.4.2.
Running tests in /usr/lib/python2.7/dist-packages/wcsaxes.

Platform: Linux-3.16.0-4-amd64-x86_64-with-debian-stretch-sid

Executable: /usr/bin/python

Full Python Version:
2.7.9 (default, Apr 29 2015, 18:34:06)
[GCC 4.9.2]

encodings: sys: ascii, locale: UTF-8, filesystem: UTF-8, unicode bits: 20
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.8.2
Scipy: not available
Matplotlib: 1.4.2
h5py: not available

That is the current debian-testing (which is mostly identical to Jessie yet).

When I do the same under Ubuntu 15.04, I get much more similar errors. Here,
the versions are

platform linux2 -- Python 2.7.9 -- pytest-2.5.1

Running tests with Astropy version 1.0.2.
Running tests in /usr/lib/python2.7/dist-packages/wcsaxes.

Platform: Linux-3.19.0-16-generic-x86_64-with-Ubuntu-15.04-vivid

Executable: /usr/bin/python

Full Python Version:
2.7.9 (default, Apr  2 2015, 15:33:21)
[GCC 4.9.2]

encodings: sys: ascii, locale: UTF-8, filesystem: UTF-8, unicode bits: 20
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.8.2
Scipy: 0.14.1
Matplotlib: 1.4.2
h5py: not available

Best

Ole

**Comment by astrofrog** [comment]
@olebole - thanks, I will look into it. I'm a little puzzled by the shift in the axes. The font is not too surprising to me, and I wonder if we could get around the issue by bundling an open font with wcsaxes for the purposes of testing.

**Comment by astrofrog** [comment]
Here's the 'actual' image @olebole sent me by email:

![ticks_labels](https://cloud.githubusercontent.com/assets/314716/9409162/a5f820c2-4818-11e5-93e9-a7359fea3f53.png)

Basically related to fonts I think.

**Comment by astrofrog** [comment]
@olebole - just out of curiosity, do you see any issues with the actual matplotlib tests? (I assume they would have similar issues?)

**Comment by astrofrog** [comment]
It looks like the Debian Matplotlib package (even 1.4.2) installs an mpl-data that matches the developer version of Matplotlib (not what mpl-data *should* contain for Matplotlib 1.4.2) and this is the source of the issue (because different fonts are being picked). Of course, since the default Matplotlib font is changing, we'll need to update the tests, but this is a weird case since the matplotlib and mpl-data versions are mismatched.

**Comment by astrofrog** [comment]
The best solution is just to switch to a font that's been there for a while and is still there, so I'll use ``cmtt10.ttf`` for the monospace and ``cmss10.ttf`` for sans-serif.

**Comment by astrofrog** [comment]
@olebole - this should be fixed now. Can you confirm that this works for you now?

**Comment by olebole** [comment]
I get the following error:
```
python2.7 setup.py test -vv --args -v
/usr/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/usr/lib/python2.7/dist-packages/astropy_helpers/setup_helpers.py:102: AstropyDeprecationWarning: Direct use of the adjust_compiler function in setup.py is deprecated and can be removed from your setup.py.  This functionality is now incorporated directly into the build_ext command.
  'command.', AstropyDeprecationWarning)
running test
running build
running build_py
/usr/lib/python2.7/dist-packages/astropy/config/configuration.py:687: ConfigurationMissingWarning: Configuration defaults will be used due to OSError:2 on None
  warn(ConfigurationMissingWarning(msg))
usage: -c [options] [file_or_dir] [file_or_dir] [...]
-c: error: unrecognized arguments: --mpl
```

**Comment by astrofrog** [comment]
@olebole - ah, it looks like you are missing the ``pytest-mpl`` package (which can be pip installed)

**Comment by olebole** [comment]
Ahh, ok. this is not in Debian yet, so I can't use it. Maybe,when I have plenty time, I will package it ;-)

**Comment by astrofrog** [comment]
@olebole - if you want to run the tests without the image tests, remove ``--mpl`` from the ``setup.cfg`` file
