### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by olebole** [astrofrog/wcsaxes#163]
Hi Thomas,

I have a request with an a bit unusual reason: I want to write a tutorial to create Debian packages for astropy affiliated packages. As example, I have chosen wcsaxes.

However, the current version is not perfect for that; mainly because the tar file contains some .pyc files (which is a no-go for a Debian package and would make the tutorial unnecessarily complicated).

Would you mind to create a new package, either a 0.3.1 without the .pyc files, or from the current state (I don't mind, since I need it just as a packaging example)?

**Comment by astrofrog** [comment]
v0.4 and v0.6 have been released since this issue was opened, so this is done
