### ISSUE TITLE
Expose CoordinateHelper.ticklabels (for those wanting to hide ticklabels)

### ISSUE THREAD

**Issue by jonathansick** [astrofrog/wcsaxes#169]
I've been using wcsaxes to make figures with a `GridSpec` of axes that show the same patch of sky, but with different images and patch distributions in each, etc.. To make the plot compact, I needed to hide the tick labels of any axis that butted up to a neighbour. The solution is simple:

```
ax.coords[i].ticklabels.set_visible(False)
```

but the problem is to figure out this was possible I had to go through the source to find out that the `coords` attribute provided a ``CoordinateHelper``, which had an undocumented attribute ``ticklabels`` that I could then treat with the usual matplotlib methods. I think what I'm doing is such a potentially common use case that perhaps it should be exposed more clearly. I see a few things that could be done:

1. Update the documentation at http://wcsaxes.readthedocs.org/en/latest/ticks_labels_grid.html with a small section on hiding ``ticklabels`` using the above method call.
2. Document the ``ticklabels`` attribute of ``CoordinateHelper``.
3. Add a method to ``CoordinateHelper`` called ``set_ticklabels_visible()``, or something like that, as a convenience.

I think 1 & 2 would be a great idea. Implementing 3 would depend on whether your want to expand the API in this direction. Let me know what you think would be good and I can make a PR.

**Comment by astrofrog** [comment]
There may be a way to do this with the current public API (not saying it's the best way, but may be cleaner for now):

```python
ax.coords[i].set_ticklabel_position('')
```

Does this work? I think ``set_ticklabels_visible()`` would be a nice addition though.

**Comment by jonathansick** [comment]
I just check and `set_ticklabel_position('')` does work. Should we document it? I feels like a bit of a hack to me, though.

**Comment by astrofrog** [comment]
@jonathansick - I agree it would be nicer to have ``set_ticklabel_visible`` (and similarly ``set_ticks_visible``) - would you be interested in implementing these? Basically they would just need to call ``set_ticklabel_position('')`` and ``set_ticks_position('')``

**Comment by jonathansick** [comment]
Sure, I'm happy to put together a PR today.

One question: shouldn't `set_ticklabel_visible()` and `set_ticks_visible()` call the equivalent `set_visible()` on the matplotilib-level object? That way one could, in principle, call `set_ticklabel_visible(True)` after a `set_ticklabel_visible(False)` and they'd come back.

Or are we more going a for a one-way, argument-less, `hide_ticklabels()` and `hide_ticks()` method?

**Comment by astrofrog** [comment]
@jonathansick - you are right, we should have it work both ways, so it makes sense to just call ``CoordinateHelper.ticks.set_visible`` and ``CoordinateHelper.ticklabels.set_visible`` behind the scenes.
