### ISSUE TITLE
Turn off tick labels

### ISSUE THREAD

**Issue by piyanatk** [astrofrog/wcsaxes#189]
There is an option to set the location of the tick labels, but can you complete turn the tick labels off, leaving only the ticks?

I have images that share the same wcs coordinates, and I want to display them using multiple subplots in the same figure, so it is a bit overkilled and using up too much space to have to repeat the tick labels.

**Comment by astrofrog** [comment]
@piyanatk - I just merged a pull request in https://github.com/astrofrog/wcsaxes/pull/170 to do this. See the documentation here: http://wcsaxes.readthedocs.org/en/latest/ticks_labels_grid.html#hiding-ticks-and-tick-labels - you'll need to install the latest developer version to get this for now though.

**Comment by piyanatk** [comment]
@astrofrog This works like a charm! Thank you!

**Comment by astrofrog** [comment]
Thanks for confirming this!
