### ISSUE TITLE
RA axis labels crowded together on all-sky axes

### ISSUE THREAD

**Issue by lpsinger** [astrofrog/wcsaxes#191]
On all-sky axes such as `MOL`, the RA axis labels are crowded together at the poles. For these sorts of axes, a better option would be to be able draw the labels on a particular line of constant declination.

``` python
import astropy.io.fits
import astropy.utils
import astropy.wcs
import wcsaxes
import numpy as np
from matplotlib import pyplot as plt
from reproject import reproject_from_healpix

url = 'https://losc.ligo.org/s/events/GW150914/P1500227/bayestar_gstlal_C01.fits.gz'
filename = astropy.utils.data.download_file(url, cache=True)

header = astropy.io.fits.Header(dict(
    NAXIS=2,
    NAXIS1=360, NAXIS2=180,
    CRPIX1=180, CRPIX2=90,
    CRVAL1=180, CRVAL2=0,
    CDELT1=-2*np.sqrt(2)/np.pi,
    CDELT2=2*np.sqrt(2)/np.pi,
    CTYPE1='RA---MOL',
    CTYPE2='DEC--MOL',
    RADESYS='ICRS').items())
wcs = astropy.wcs.WCS(header)

img, _ = reproject_from_healpix(filename, header)
ax = plt.axes(projection=wcs, frame_class=wcsaxes.frame.EllipticalFrame)
ax.imshow(img, origin='lower', cmap='OrRd')
ax.grid()
plt.savefig('gw151226.png')
```

![gw151226](https://cloud.githubusercontent.com/assets/728407/13309320/b26d2aae-db49-11e5-8ccc-ccfeacea9714.png)

**Comment by astrofrog** [comment]
@lpsinger - great idea, and this could be useful even for more normal plots. Would you be interested in working on this? :)

There are currently two ways to plot grid lines - one is by plotting lines directly, and the other is to use contours. In either case, there may be ways built-in to Matplotlib to add text along a path.

**Comment by lpsinger** [comment]
I'm not sure how to get started. Is there an example that shows how to plot axis labels along arbitrary paths?

**Comment by astrofrog** [comment]
@lpsinger - I'm not sure either, but in WCSAxes we use the ``Path`` class to plot the grid lines by default, so it would be worth checking in the Matplotlib gallery for example if there is a way to plot text that follows paths. I can try and investigate this too, but won't be able to do for the next week or so.

**Comment by lpsinger** [comment]
Matplotlib's axes base class defines several methods to be defined by subclasses: `get_xaxis_transform`, `get_xaxis_text1_transform`, `get_xaxis_text2_transform`, and the corresponding methods for the y axis. The built-in Matplotlib [polar](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/projections/polar.py) and [geographic](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/projections/geo.py) projections illustrate how these methods control axis label positioning and placement.

However, overriding these methods will probably not work for wcsaxes because the ticks and tick labels are rendered by hand in the `Ticks` and `TickLabels` classes. None of the examples in the docs have ticks and tick labels that are inside the frame. Do you have any suggestions for what the API for this should look like?
