### ISSUE TITLE
pip install broken for wcsaxes v0.8 for Python 3.5.2

### ISSUE THREAD

**Issue by cdeil** [astrofrog/wcsaxes#206]
`pip install wcsaxes` is broken for v0.8 with Python 3.5.2:
```
$ pip install wcsaxes
Collecting wcsaxes
  Using cached wcsaxes-0.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sb/4qv5j4m90pz1rw7m70rj1b1r0000gn/T/pip-build-daax2opt/wcsaxes/setup.py", line 25, in <module>
        conf = config.ConfigParser()
    AttributeError: module 'distutils.config' has no attribute 'ConfigParser'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/sb/4qv5j4m90pz1rw7m70rj1b1r0000gn/T/pip-build-daax2opt/wcsaxes/
```

@astrofrog - Could you please put the configparser import fixes from  https://github.com/astropy/package-template/pull/172 and https://github.com/astropy/package-template/pull/180 and release a new stable version?

**Comment by cdeil** [comment]
Same request for APLPy ... please release a new version with this fix.

I need to install it on several machines and having a PyPI stable version that works is so helpful.
```
```
$ pip install aplpy --user
Collecting aplpy
  Downloading APLpy-1.0.tar.gz (1.2MB)
    100% |████████████████████████████████| 1.2MB 800kB/s 
    Complete output from command python setup.py egg_info:
    /opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
      warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
    /opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
      warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sb/4qv5j4m90pz1rw7m70rj1b1r0000gn/T/pip-build-7evkx3gs/aplpy/setup.py", line 25, in <module>
        conf = config.ConfigParser()
    AttributeError: module 'distutils.config' has no attribute 'ConfigParser'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/sb/4qv5j4m90pz1rw7m70rj1b1r0000gn/T/pip-build-7evkx3gs/aplpy/
```

**Comment by astrofrog** [comment]
@cdeil - would you by any chance have time to do a PR to these projects with the fix? :) It's going to be hard for me to do this in the next couple of days, although I'd be happy to put time aside to do the release if someone can open a PR with the fix :)

**Comment by cdeil** [comment]
> would you by any chance have time to do a PR to these projects with the fix?

yes.

**Comment by astrofrog** [comment]
Thanks! :)

**Comment by astrofrog** [comment]
@cdeil - I just released v0.9 - can you confirm this can be closed?

**Comment by cdeil** [comment]
Yes, it's fixed. Sorry I didn't get to this PR. Thank you!

**Comment by bsipocz** [comment]
@cdeil - Just as a related note, the conda package for v0.9 should be available soon on the astropy channel.

**Comment by bsipocz** [comment]
@astrofrog - It's quite irregularly timed atm to check the latest versions and update the conda packages, but if you ping me after a release is made, I'll try to make the updates sooner. On the long term it would be nice to write a bot for it, but I would feel very guilty to spend much time on it now.

**Comment by astrofrog** [comment]
@bsipocz - ah sorry I forgot about the astropy channel - I triggered the build on conda-forge straight away.

**Comment by bsipocz** [comment]
No worries. I didn't know that this is on conda-forge :)
