### ISSUE TITLE
Add link to WCSAxes on Matplotlib mapping toolkits page

### ISSUE THREAD

**Issue by lpsinger** [astrofrog/wcsaxes#212]
The Matplotlib documentation contains a [list of Matplotlib mapping toolkits](http://matplotlib.org/mpl_toolkits/index.html#mapping-toolkits). Seems like wcsaxes should be represented there.

**Comment by astrofrog** [comment]
I opened a PR here: https://github.com/matplotlib/matplotlib/pull/9732
