### ISSUE TITLE
Remove this package from Astropy affiliated list?

### ISSUE THREAD

**Issue by pllim** [astrofrog/wcsaxes#217]
I still see it listed in http://www.astropy.org/affiliated/

**Comment by bsipocz** [comment]
I would definitely wait for any such removal at least until the new LTS is out. You still need wcsaxes as a separate package for anything that uses/supports astropy <1.3

**Comment by bsipocz** [comment]
@astrofrog -Is there a decision by the committee on affiliate deprecation yet?  Should we move this issue to the astropy webpage repo to do at the time of v2.0 release?
